### ISSUE TITLE
Añadir un tipo de licencia al proyecto

### ISSUE THREAD

**Issue by javipuche** [javipuche/project-g#2]
Habría que buscar un tipo de licencia adecuado para el proyecto.

[Información de algunas licencias](https://choosealicense.com/)
[Tipos de licencia Creative Commons](https://www.upo.es/biblioteca/servicios/pubdig/propiedadintelectual/tutoriales/derechos_autor/htm_12.htm)

**Comment by javipuche** [comment]
Yo optaría por una licencia en la cual se pueda usar nuestro código, trastear con él, poder publicarlo pero nunca con fines comerciales. El tipo de licencia creative commons by-nc-sa creo que estaría bien.

**Comment by jjlmoya** [comment]
Creo que es la mejor opción, no veo otra que pueda encajar bien. Por mi by-nc-sa
